version: '3'
services:
  jenkins:
    container_name: jenkins
    image:  jenkins/jenkins
    ports:
      - "8085:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    deploy:
      resources:
        limits:
          cpus: '300'
          memory: 3560M
        reservations:
          memory: 512M
    networks: 
      - net
  
networks: 
  net: